# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-06 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='acc_balance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
