# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-06 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_auto_20170506_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='acc_balance',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='acc_number',
            field=models.BigIntegerField(),
        ),
    ]
